name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '16.x'
      - run: echo "npm run build"
      - run: npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."